apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: db-secrets-sync
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: db-secrets  # Nombre del secreto que generará automáticamente
    namespace: databases
    type: Opaque

---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: traefik-dashboard-sync
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: traefik-dashboard-auth
    namespace: kube-system
    type: Opaque
  secrets:
    - TRAEFIK_DASHBOARD_USERS
  processors:
    TRAEFIK_DASHBOARD_USERS:
      type: plain
      asName: .htpasswd

---

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: duckdns-secret-sync
  namespace: kube-system
spec:
  tokenSecret:
    name: doppler-token-auth
    namespace: doppler-operator-system
  project: mi-dev-stack
  config: dev
  managedSecret:
    name: duckdns-credentials
    namespace: kube-system
    type: Opaque
