apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      postgres:
        port: 6432
        exposedPort: 6432
        protocol: TCP
    additionalArguments:
      - "--entrypoints.postgres.address=:6432/tcp"
      - "--certificatesresolvers.letsencrypt-prod.acme.email=francisco.heral02@gmail.com"
      - "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt-prod.acme.httpchallenge.entrypoint=web"
