name: Deploy base configs

on:
  workflow_dispatch:
    inputs:
      componente:
        description: '¿Qué componente desplegar?'
        required: true
        type: choice
        options:
          - all        # Despliega todo lo que esté en la carpeta k8s/
          - db-stack
          - ingress
          - apps
      namespace:
        description: 'Namespace principal para verificación'
        required: true
        default: 'databases'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Contexto de Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Desplegar a K3s
        run: |
          if [[ "${{ inputs.componente }}" == "all" ]]; then
            echo "🚀 Desplegando TODO el contenido de la carpeta k8s/..."
            # --recursive aplica todos los .yaml dentro de la carpeta
            kubectl apply -f k8s/ --recursive
          else
            echo "🛠️ Desplegando archivo específico: k8s/${{ inputs.componente }}.yaml"
            kubectl apply -f k8s/${{ inputs.componente }}.yaml
          fi
          
      - name: Verificar Rollout (Solo para DB)
        # Se ejecuta si elegiste 'all' o 'db-stack'
        if: contains(inputs.componente, 'db') || inputs.componente == 'all'
        run: |
          echo "Verificando salud de la base de datos..."
          kubectl rollout status deployment/postgres-db -n ${{ inputs.namespace }} --timeout=60s
          kubectl rollout status deployment/pgbouncer -n ${{ inputs.namespace }} --timeout=60s

      - name: Resumen de recursos
        run: |
          kubectl get pods,svc -n ${{ inputs.namespace }}
          # Si usas otros namespaces (como para ingress), podrías listarlos aquí también
